apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-github
  namespace: atlantis
  annotations:
    description: "GitHub credentials for Atlantis webhook"
    argocd.argoproj.io/tracking-id: "atlantis-github"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: atlantis-github
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: nexus/atlantis-github
        property: username
    - secretKey: token
      remoteRef:
        key: nexus/atlantis-github
        property: token
    - secretKey: webhook-secret
      remoteRef:
        key: nexus/atlantis-github
        property: webhook-secret
